name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12', '14']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm t --coverage
          npm run build --if-present
        env:
          CI: true
          NODE_ENV: production
          NODE_OPTIONS: '--trace-warnings'
